apiVersion: v1
kind: Service
metadata:
  name: outerspace-server
  labels:
    app: outerspace-server
spec:
  selector:
    app: outerspace-server
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: grpc
    port: 50053
    targetPort: 50053
    protocol: TCP
  type: ClusterIP