name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io

jobs:
  test-and-build-go:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    - name: Setup proxymock
      env:
        PROXYMOCK_API_KEY: ${{ secrets.PROXYMOCK_API_KEY }}
      run: |
        mkdir -p .speedscale
        curl -Lfs https://downloads.speedscale.com/proxymock/install-proxymock | sh
        echo "$HOME/.speedscale" >> $GITHUB_PATH
        $HOME/.speedscale/proxymock init --api-key "$PROXYMOCK_API_KEY"
    - name: Install dependencies
      run: go mod download
    - name: Run unit tests
      run: make test
    - name: Run integration tests
      run: make integration-test
    - name: Run load tests
      run: make load-test
