name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    # - name: Run proxymock
    #   env:
    #     PROXYMOCK_API_KEY: ${{ secrets.PROXYMOCK_API_KEY }}
    #   run: .github/workflows/runMock.sh

    - name: Install dependencies
      run: go mod download

    # - name: Run integration tests with proxymock
    #   run: |
    #     export http_proxy=socks5h://localhost:4140
    #     export https_proxy=socks5h://localhost:4140
    #     export SSL_CERT_FILE=~/.speedscale/certs/tls.crt
    #     go test -v ./...
    
    - name: Run integration tests without proxymock
      run: go test -v ./...
      
    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3
    
    # - name: Log in to the Container Registry
    #   uses: docker/login-action@v3
    #   with:
    #     registry: ${{ env.REGISTRY }}
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    #     logout: false

    # - name: Build and Push
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     platforms: linux/amd64,linux/arm64
    #     push: true
    #     tags: ghcr.io/kenahrens/outerspace-go:latest
